sudo: required

language: c

compiler:
  - clang
  - gcc

before_install:
  - pip install --user cpp-coveralls

script: make coverage=yes 

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'