sudo: required

language: c

compiler:
  - clang
  - gcc

before_install:
  - pip install --user cpp-coveralls

script: make coverage=yes 

after_success:
  - ./test/repeate_timer_test
  - ./test/multi_timer_test
  - tree
  - coveralls --exclude ./test/ --exclude ./example/ --gcov-options '\-blp'