sudo: required

language: c

compiler:
  - clang
  - gcc

before_install:
  - pip install --user cpp-coveralls

script: make coverage=yes 

after_success:
  - coveralls --exclude ./example/sample_demo --gcov-options '\-b \-s ./src'